// THIS FILE (sysfs-paths.h) IS AUTOMATICALLY GENERATED BY ./build_paths.sh
#ifndef SYSFS_PATHS_H
#define SYSFS_PATHS_H
#define PWM_PATH "/sys/devices/ocp.3/pwm_test_P8_34.12/"
#define GPIO_MOTORDIR_PATH "/sys/class/gpio/gpio70/"
#define GPIO_STBY_PATH     "/sys/class/gpio/gpio73/"
#define EQEP_PATH "/sys/devices/ocp.3/48302000.epwmss/48302180.eqep/"
#endif // header guard
